#!/bin/sh
# Tests for `luma-foreman bundle index` — the INDEX.md generator and its
# check mode.
#
#   sh tests/bundle-index-test.sh
#
# The index is a rendering and the frontmatter is authoritative, so the two
# properties worth holding are: the same state always renders the same index,
# and --check is regenerate-and-compare, which cannot disagree with the
# generator. Plus the boundary that matters most: generation is an authoring
# act, and a vendored copy is refused rather than quietly re-rendered.
set -u

ROOT=$(cd "$(dirname "$0")/.." && pwd -P)
CLI=${LUMA_FOREMAN_CLI:-$ROOT/bin/luma-foreman}
export PYTHONDONTWRITEBYTECODE=1

T=$(mktemp -d /tmp/bundle-index.XXXXXX) || exit 2
trap 'rm -rf "$T"' EXIT INT TERM

pass=0 fail=0
ok()  { pass=$((pass + 1)); }
bad() { fail=$((fail + 1)); printf 'FAIL  %s\n' "$1"; }

grepped() { grep -q -- "$1" "$2" 2>/dev/null && ok || bad "expected '$1' in $(basename "$2")"; }
ungrep()  { grep -q -- "$1" "$2" 2>/dev/null && bad "expected '$1' NOT in $(basename "$2")" || ok; }

B=$T/git-secrets
mkdir -p "$B/policy" "$B/reference" "$B/procedure" "$B/templates" "$B/notes"

cat > "$B/BUNDLE.md" <<'EOF'
---
type: bundle
title: lumastack/luma-catalog/git-secrets
version: 0.5.1
description: Keeping credentials and private identity out of a repository.
---

# Git secrets

Start with identity; credentials follow.
EOF

cat > "$B/policy/never-commit-credentials.md" <<'EOF'
---
type: policy
title: Never commit credentials
description: What counts as a credential, and why rotation comes before cleanup.
matches:
  - command: git commit
  - command: git push
  - event: before-commit
---
Body.
EOF

cat > "$B/policy/never-commit-private-identity.md" <<'EOF'
---
type: policy
title: Never commit private identity
description: Real names and home paths must not appear in tracked content.
matches: eager
---
Body.
EOF

cat > "$B/reference/scrubbing-history.md" <<'EOF'
---
type: document
title: Scrubbing history
description: What removing something from git history actually takes.
---
Body.
EOF

cat > "$B/procedure/audit-sensitive-data.md" <<'EOF'
---
type: procedure
title: Audit sensitive data
description: Check whether a repository already published credentials.
---
Steps.
EOF

cat > "$B/notes/legacy.md" <<'EOF'
---
type: document
title: Legacy
description: Declares the retired keyword.
matches: always
---
Body.
EOF

cat > "$B/templates/skip.md" <<'EOF'
---
type: document
title: A template
---
Excluded by path.
EOF

printf 'no frontmatter — an Asset, not a Document\n' > "$B/notes/raw.md"

# -- generation ---------------------------------------------------------------

ERR=$T/stderr
"$CLI" bundle index "$B" >/dev/null 2>"$ERR"
[ $? -eq 0 ] && ok || bad "generate should exit 0"
IX=$B/INDEX.md
[ -f "$IX" ] && ok || bad "INDEX.md should exist"

grepped 'Generated by `luma-foreman bundle index`' "$IX"
grepped '# lumastack/luma-catalog/git-secrets 0.5.1' "$IX"
grepped 'Keeping credentials and private identity' "$IX"
grepped 'Start with identity; credentials follow.' "$IX"
ungrep  '# Git secrets' "$IX"

grepped '## Required — do NOT act on this bundle before reading these' "$IX"
grepped 'policy/never-commit-private-identity' "$IX"
grepped 'matches: eager' "$IX"

grepped '## Offered — open when the work matches' "$IX"
grepped 'matches: command:git commit, command:git push, event:before-commit' "$IX"

grepped '## By request — reached by name or by citation' "$IX"
grepped 'reference/scrubbing-history' "$IX"

grepped 'Procedures in `procedure/` are installed in your harness' "$IX"
ungrep  'audit-sensitive-data' "$IX"
ungrep  'templates/skip' "$IX"
ungrep  'notes/raw' "$IX"

# The retired keyword is reported and the Document fails safe, to By request.
grepped "unknown matches keyword 'always'" "$ERR"
grepped 'notes/legacy' "$IX"

# -- determinism and check ----------------------------------------------------

cp "$IX" "$T/first"
"$CLI" bundle index "$B" >/dev/null 2>/dev/null
cmp -s "$IX" "$T/first" && ok || bad "two generations should be byte-identical"

"$CLI" bundle index "$B" --check >/dev/null 2>&1
[ $? -eq 0 ] && ok || bad "--check should pass on a fresh generation"

printf 'hand edit\n' >> "$IX"
"$CLI" bundle index "$B" --check >/dev/null 2>&1
[ $? -eq 1 ] && ok || bad "--check should fail on a hand-edited index"

rm "$IX"
"$CLI" bundle index "$B" --check >/dev/null 2>&1
[ $? -eq 1 ] && ok || bad "--check should fail when the index is missing"

"$CLI" bundle index "$B" >/dev/null 2>/dev/null
"$CLI" bundle index "$B" --check >/dev/null 2>&1
[ $? -eq 0 ] && ok || bad "--check should pass again after regeneration"

# -- boundaries ---------------------------------------------------------------

# Not a bundle at all.
mkdir -p "$T/empty"
"$CLI" bundle index "$T/empty" >/dev/null 2>&1
[ $? -eq 2 ] && ok || bad "a directory with no BUNDLE.md should refuse (2)"

# A vendored copy is refused; a local bundle in the same tree is not.
P=$T/proj
mkdir -p "$P/.luma/bundles/org/vendored" "$P/.luma/bundles/org/local"
cat > "$P/.luma/bundles/org/vendored/BUNDLE.md" <<'EOF'
---
type: bundle
title: org/vendored
version: 1.0.0
description: A vendored copy.
---
EOF
cat > "$P/.luma/bundles/org/local/BUNDLE.md" <<'EOF'
---
type: bundle
title: org/local
version: 0.1.0
description: Written here, never adopted.
---
EOF
cat > "$P/.luma/bundles/adopted.toml" <<'EOF'
["org/vendored"]
version = "1.0.0"
source = "https://catalog.invalid/example"
commit = "0000000000000000000000000000000000000000"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
EOF

"$CLI" bundle index "$P/.luma/bundles/org/vendored" >/dev/null 2>"$ERR"
[ $? -eq 2 ] && ok || bad "a vendored copy should be refused (2)"
grepped 'vendored copy' "$ERR"

"$CLI" bundle index "$P/.luma/bundles/org/local" >/dev/null 2>&1
[ $? -eq 0 ] && ok || bad "a local bundle under .luma/bundles should generate"

printf '%d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
