"""Putting the gate where Claude Code will run it.

Two rules shape this, both learned the hard way.

Write freely into the directory foreman owns; never silently edit the directory
the user owns. So the gate is installed for you and the settings.json changes
are printed. That follows `pre-commit install`, and it matters more here than
usual because settings.json holds the operator's own permission rules.

Be self-contained. An earlier design had the installed gate exec the Python in
a checkout. Move or delete the checkout and `exec` fails, the hook exits
non-zero, and Claude Code treats that as a non-blocking error — so the tool call
proceeds. The gate would fail OPEN because a directory moved. Installing a copy
removes that failure mode entirely.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

from . import store

# The shim checks its own prerequisites and emits an "ask" if they are missing,
# rather than exiting non-zero — a hook that errors is a hook Claude Code
# ignores, and being ignored is the one thing a permission gate must never do.
SHIM = """#!/bin/sh
# Generated by `luma-foreman policy install` — do not edit.
# Reinstall to update. This file decides what an agent is allowed to do.
dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
refuse() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":"Permission gate cannot run: %s"}}' "$1"
  exit 0
}
[ -f "$dir/gate/run.py" ] || refuse "gate files are missing; run luma-foreman policy install"
command -v python3 >/dev/null 2>&1 || refuse "python3 not found"
# -B: never write bytecode. The gate would otherwise litter __pycache__
# through its own install directory, inside the deny rule that protects it.
exec python3 -B "$dir/gate/run.py" "$@"
"""

RUNNER = """#!/usr/bin/env python3
# Generated by `luma-foreman policy install` — do not edit.
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from foreman.policy.gate import main  # noqa: E402

raise SystemExit(main())
"""

# Only what the gate imports. Keeping this explicit means an accidental new
# dependency in gate.py shows up as a missing module at install time, not as a
# gate that silently fails on someone else's machine.
GATE_MODULES = (
    "__init__.py",
    "project.py",
    "policy/__init__.py",
    "policy/model.py",
    "policy/store.py",
    "policy/match.py",
    "policy/gate.py",
)


def package_root() -> Path:
    return Path(__file__).resolve().parent.parent


def gate_path() -> Path:
    """The installed gate: program data, not configuration."""
    return store.data_home() / "permission-gate.sh"


def _payload() -> dict[Path, str]:
    """Every file install writes, and its content. Used to write and to compare."""
    src = package_root()
    data = store.data_home()
    files: dict[Path, str] = {
        gate_path(): SHIM,
        data / "gate" / "run.py": RUNNER,
    }
    for rel in GATE_MODULES:
        files[data / "gate" / "foreman" / rel] = (src / rel).read_text()
    return files


def status() -> str:
    """'installed' | 'updated' | 'already current'"""
    if not gate_path().exists():
        return "installed"
    for path, text in _payload().items():
        if not path.exists() or path.read_text() != text:
            return "updated"
    return "already current"


def install() -> str:
    verb = status()
    if verb != "already current":
        for path, text in _payload().items():
            path.parent.mkdir(parents=True, exist_ok=True)
            tmp = path.with_name(f".{path.name}.tmp")
            tmp.write_text(text)
            os.replace(tmp, path)
        gate_path().chmod(0o755)
        (store.data_home() / "gate" / "run.py").chmod(0o755)
    # The policy directory is configuration and lives elsewhere on purpose.
    (store.home() / "projects").mkdir(parents=True, exist_ok=True)
    return verb


def legacy_install() -> Path | None:
    """A gate left behind by the pre-XDG layout, or None.

    Worth reporting rather than deleting: settings.json may still point at it,
    and removing it before the wiring moves would leave the session unguarded.
    """
    old = store.legacy_gate()
    return old if old.exists() else None


def settings_path() -> Path:
    return Path(os.environ.get("CLAUDE_CONFIG_DIR") or (Path.home() / ".claude")) / "settings.json"


_HOME_FORMS = (("${HOME}", None), ("$HOME", None), ("~", None))


def _normalise(command: str) -> str:
    """A hook command is a shell string, so one path has several legitimate spellings.

    Normalising before comparison stops a correctly wired setup reading as
    unwired — which it did, the first time this check existed.
    """
    text = command.replace('"', "")
    home = str(Path.home())
    text = text.replace("${HOME}", home).replace("$HOME", home)
    if text.startswith("~"):
        text = home + text[1:]
    return text


def wiring() -> dict[str, object]:
    """What settings.json currently says, without changing it."""
    path = settings_path()
    result: dict[str, object] = {
        "settings": str(path),
        "exists": path.exists(),
        "hook_ok": False,
        "deny_ok": False,
        "stale_hook": False,
    }
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return result

    commands = [
        h.get("command", "")
        for entry in (data.get("hooks", {}).get("PreToolUse") or [])
        for h in (entry.get("hooks") or [])
    ]
    target = str(gate_path())
    result["hook_ok"] = any(target in _normalise(c) for c in commands)
    if not result["hook_ok"]:
        result["stale_hook"] = any("permission-gate" in c for c in commands)
    deny = data.get("permissions", {}).get("deny") or []
    result["deny_ok"] = any("luma" in str(rule) for rule in deny)
    return result


def snippet() -> str:
    return f"""  {{
    "permissions": {{
      "deny": ["Edit(~/.config/luma/**)", "Edit(~/.local/share/luma/**)"]
    }},
    "hooks": {{
      "PreToolUse": [
        {{
          "matcher": "Bash|Read|Write|Edit|MultiEdit|NotebookEdit",
          "hooks": [
            {{ "type": "command", "command": "{gate_path()}" }}
          ]
        }}
      ]
    }}
  }}"""
