"""Projecting what a project adopted into what its harness actually reads.

**Adoption puts knowledge in the repository; nothing yet puts it in front of an
agent.** A bundle in `.luma/bundles/` is inert until something tells Claude Code
that it exists, and telling it is harness-specific work that the bundle must not
have to know about.

**Thin adapters, and thin is the whole design.** What gets written is a pointer
and a reason to follow it — never a copy of the document. A copy would be a
second source of truth that drifts from the first, and it would charge every
session for content that was supposed to load only when the work matched.

Two outputs, because a harness has two ways in:

| | |
| --- | --- |
| **skills** | one per `workflow`, so an agent can be *asked* to do the thing |
| **the entrypoint** | `.luma/bundles/entrypoint.md` — the project ring, naming what exists and what brings each part into play |
| **the adapter** | a block in `CLAUDE.md` that points at the entrypoint and carries nothing else |

**The entrypoint is the part that closes the gap.** Everything else assumes
somebody already knows the knowledge is there. Make existence cheap and content
expensive, so a consumer can always see what it is *not* loading.

**The adapter is separate from the ring on purpose.** A ring is the same thing
whatever is reading it, and a harness's file is not — so the ring is written
once and each harness gets a pointer. The adapter's one obligation beyond
pointing is to **not render what its harness already carries**: workflows reach
Claude Code as skills, whose names and descriptions it loads at startup, so the
ring does not list them a second time.

Everything written here is generated and disposable. The source is `.luma/`.
"""

from __future__ import annotations

import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from . import adoption, lkf, project

USAGE = """Project adopted bundles into what this project's harness reads.

  luma-foreman apply             write the skills, the entrypoint and the adapter
  luma-foreman apply --check     report what would change, write nothing
  luma-foreman apply --explain   show what each Document derives to, and from what
  luma-foreman apply --to <dir>  a project other than this repository

Writes .claude/skills/<name>/SKILL.md for every workflow, .luma/bundles/entrypoint.md
naming everything adopted, and a managed block in CLAUDE.md pointing at it. All are
generated from .luma/ and are disposable — regenerate them rather than editing them.

Exit codes: 0 written (or up to date), 1 --check found staleness, 2 could not run."""

# Written into every generated file. It is what makes a later run able to tell
# what it owns from what somebody wrote by hand, which is what lets a skill for
# an un-adopted bundle actually leave.
MARK = "luma-foreman:generated"

# Only BEGIN_MARK is matched when locating an existing block. The rest of the
# line is prose and has been reworded once already — matching the whole string
# meant the rename orphaned the old block and appended a second one beside it.
BEGIN_MARK = "<!-- luma:begin"
BEGIN = f"{BEGIN_MARK} — generated by `luma-foreman apply`. Edits between these markers are lost. -->"
END = "<!-- luma:end -->"

# The project ring. It lives beside `adopted.toml` and `routing.toml` because
# all three are derived from what is in force and change exactly when it does —
# which is the lifecycle the tiers are cut by. The name is expected to move once
# there is something to look at; nothing depends on it but this line.
ENTRYPOINT = Path(".luma/bundles/entrypoint.md")

# `_types/` holds contracts, not reading material — a Type Definition is
# consulted when writing a document of that type, which is a job the workflow
# already sends you to. Listing them would double the index to say nothing.
SKIP = ("_types",)

SLUG = re.compile(r"[^a-z0-9-]+")

# Skill names foreman writes itself. Reserved, because they are the only route
# to a ring that does not depend on anything noticing — and a workflow quietly
# taking one would remove the floor the rest of the design stands on.
NAVIGATION = ("list-bundles", "load-bundle")

# What this build can actually do at the moment a rule is broken. The vocabulary
# is larger — `audit`, `warn`, `require_reason`, `require_approval` all mean
# something — and none of the rest is implemented. A declaration this cannot
# honour is refused rather than quietly downgraded to the nearest thing that
# works, because a rule that silently becomes weaker than it says is the exact
# failure the whole design exists to remove.
SUPPORTED_ON_VIOLATION = ("allow", "block")

# `README.md` is deliberately not an owner, whatever it contains. It carries
# universal permission semantics — everybody believes they may edit it freely —
# so a system that depends on its structure has a fuse in it, lit by the next
# person who tidies up.
NEVER_OWNS = ("README",)


def _owns_directory(path: Path) -> bool:
    """Is this the all-caps Document that its directory *is*?

    The casing is the signal rather than any particular word, so a workflow gets
    `WORKFLOW.md` and somebody's own type gets its own — nothing is centrally
    reserved, which the open type vocabulary requires.
    """
    stem = path.stem
    return stem.isupper() and stem not in NEVER_OWNS


@dataclass(frozen=True)
class Doc:
    """A Document inside a vendored bundle, as writing it out needs it."""

    bundle: str
    doc_id: str
    path: Path
    type: str
    title: str
    description: str
    on_violation: str
    matches: tuple[str, ...]
    legacy_preload: str = ""

    @property
    def slug(self) -> str:
        return SLUG.sub("-", self.doc_id.rsplit("/", 1)[-1].lower()).strip("-")

    @property
    def klass(self) -> str:
        """Where this lands: always-on, advertised, or on-demand.

        Derived, never declared — but **the expensive outcome is asked for
        rather than fallen into**. `matches: always` is the only route to
        always-on, so a Document cannot acquire a permanent seat in every
        session because somebody forgot a field.

        **The type no longer decides anything here**, and that is a
        simplification rather than an omission. It used to break the tie for a
        Document with no trigger — policy meant loaded-always, anything else
        meant findable. With the default reversed there is no tie: nothing
        surfaces a Document that says nothing surfaces it, whatever its type.

        **An unknown keyword lands here as on-demand**, which is the safe
        direction. `inspect` names it; the alternative is a typo buying a
        permanent seat in everybody's context.
        """
        if self.matches == ("always",):
            return "always-on"
        return "advertised" if self.matches else "on-demand"


@dataclass(frozen=True)
class Bundle:
    """A vendored bundle and the Documents worth projecting."""

    bundle_id: str
    root: Path
    version: str
    description: str
    docs: tuple[Doc, ...]
    entrypoint: str = ""

    def of_type(self, kind: str) -> list[Doc]:
        return [d for d in self.docs if d.type == kind]

    def of_class(self, klass: str) -> list[Doc]:
        return [d for d in self.docs if d.klass == klass]

    def always_on(self) -> list[Doc]:
        """Documents whose bodies have to be present before work starts."""
        return self.of_class("always-on")


def _text(keys: dict[str, str], name: str) -> str:
    return lkf.unquote(keys.get(name, "")).strip()


def discover(project_root: Path) -> list[Bundle]:
    """Every bundle in `.luma/bundles/`, adopted or written here.

    Both are written out. What a project wrote for itself is as much a part of how
    it works as what it took from a catalog, and an agent has no reason to care
    which is which — that distinction matters to drift checking, not to loading.
    """
    root = adoption.bundles_dir(project_root)
    if not root.is_dir():
        return []

    out: list[Bundle] = []
    for bundle_id, home in adoption.discover(project_root).items():
        manifest = home / "BUNDLE.md"
        keys = lkf.read(manifest) or {}

        # A directory that *is* a Document owns everything beneath it. Its
        # subordinates — a tutorial's steps, a template beside the workflow that
        # copies it — are reachable only through the owner and never announced
        # separately. That is the whole of subordination: no field, no
        # declaration, just where a file sits.
        owned: dict[Path, Path] = {}
        for path in sorted(home.rglob("*.md")):
            # The bundle's own manifest owns the bundle directory by exactly
            # this rule — and must not hide it. A bundle's members are its
            # content, which is the thing being written out; subordination
            # applies *within* a bundle, never at its root.
            if path.parent == home:
                continue
            if _owns_directory(path):
                owned[path.parent] = path

        def owner_of(path: Path) -> Path | None:
            for parent in path.parents:
                if parent in owned and owned[parent] != path:
                    return owned[parent]
                if parent == home:
                    break
            return None

        docs: list[Doc] = []
        for path in sorted(home.rglob("*.md")):
            rel = path.relative_to(home)
            if rel.parts[0] in SKIP or rel.as_posix() == "BUNDLE.md":
                continue
            if owner_of(path) is not None:
                continue  # subordinate: it arrives with its owner or not at all
            front = lkf.read(path)
            if front is None or "type" not in front:
                continue  # an Asset — a template, an example. Not addressable.

            # The directory is the identity. `WORKFLOW.md` is a local detail
            # nothing references, visible only to somebody already standing in
            # the directory — so the ID, the skill name and every link shorten
            # to the directory that holds it.
            doc_id = rel.parent.as_posix() if _owns_directory(path) else rel.as_posix()[:-3]

            docs.append(
                Doc(
                    bundle=bundle_id,
                    doc_id=doc_id,
                    path=path,
                    type=_text(front, "type"),
                    title=_text(front, "title"),
                    description=_text(front, "description"),
                    on_violation=_text(front, "on_violation") or "allow",
                    matches=lkf.matches(path),
                    legacy_preload=_text(front, "preload"),
                )
            )

        out.append(
            Bundle(
                bundle_id=bundle_id,
                root=home,
                version=_text(keys, "version"),
                description=_text(keys, "description"),
                docs=tuple(docs),
                # Both spellings while the rename finishes. A bundle that has
                # not been republished still has an answer to *where do I
                # start*, and reading only the new key would discard it.
                entrypoint=_text(keys, "entrypoint") or _text(keys, "entry_point"),
            )
        )
    return out


# --------------------------------------------------------------------------
# skills


def _skill(doc: Doc, bundle: Bundle, project_root: Path) -> str:
    """One adapter: harness frontmatter, and where the real document is."""
    source = doc.path.relative_to(project_root).as_posix()
    lines = [
        "---",
        f"name: {doc.slug}",
        f"description: {doc.description}",
        "---",
        "",
        f"<!-- {MARK} from {bundle.bundle_id} {doc.doc_id}. "
        f"Regenerate with `luma-foreman apply`; edits are lost. -->",
        "",
        f"# {doc.title or doc.slug}",
        "",
        f"**Read `{source}` and follow it.** That file is the workflow. This is "
        f"the adapter that makes it reachable from here, and it deliberately "
        f"carries no copy of it — the copy would drift.",
    ]

    always_on = [d for d in bundle.always_on() if d.doc_id != doc.doc_id]
    if always_on:
        lines += ["", "Always-on context this workflow assumes:", ""]
        for d in always_on:
            rel = d.path.relative_to(project_root).as_posix()
            lines.append(f"- `{rel}` — {d.description or d.title or d.doc_id}")

    lines += [
        "",
        f"From the `{bundle.bundle_id}` bundle, vendored at "
        f"`{bundle.root.relative_to(project_root).as_posix()}/`. Do not edit "
        f"anything under there — an adopted bundle is a copy, and editing it is "
        f"drift.",
        "",
    ]
    return "\n".join(lines)


def _generated(skills: Path) -> dict[str, Path]:
    """Skill directories a previous run wrote, keyed by name."""
    if not skills.is_dir():
        return {}
    out = {}
    for path in sorted(skills.glob("*/SKILL.md")):
        try:
            if MARK in path.read_text(encoding="utf-8"):
                out[path.parent.name] = path.parent
        except (OSError, UnicodeDecodeError):
            continue
    return out


def _navigation(bundles: list[Bundle]) -> dict[str, str]:
    """The two skills that fire a ring on purpose rather than by noticing.

    **This is the floor.** Every other route depends on something matching — a
    trigger firing, a description catching a model's attention — and all of
    them degrade quietly when they do not. Asking by name cannot: it works when
    nothing notices, which is why it is built before any automatic firing and
    why its names are reserved.

    **Two skills, not one per bundle.** The cost is fixed however many bundles
    a project holds, so nothing here scales with adoption.
    """
    ring = ENTRYPOINT.as_posix()
    return {
        "list-bundles": f"""---
name: list-bundles
description: List the knowledge bundles this project has adopted, and what each one is for. Use when deciding which one to open, or when asked what this project knows.
---

<!-- {MARK} navigation. Regenerate with `luma-foreman apply`; edits are lost. -->

# What this project knows

Read `{ring}`. It names every adopted bundle, what each is for, and the path to
its ring.

**It is not copied here on purpose.** That file already arrives at the start of
a session, and rendering it a second time would charge twice for one list. What
this skill is for is the moment it has fallen out of context and you need it
back — so read the file, which is current, rather than a copy, which would not
be.

**This lists what is adopted, not what exists.** Bundles this project has not
taken are in whatever catalog it draws on, and nothing here can see them —
`luma-foreman catalog show <catalog>` is the command that can.
""",
        "load-bundle": f"""---
name: load-bundle
description: Open one adopted bundle and see what it holds — its rules, what fires each one, and anything that applies throughout it. Use when a bundle's line looks relevant, or when asked to load a bundle by name.
---

<!-- {MARK} navigation. Regenerate with `luma-foreman apply`; edits are lost. -->

# Open a bundle

Read `.luma/bundles/rings/<bundle-id>.md`.

**The bundle ID carries its namespace** — `lumastack/luma-catalog/git-secrets`,
never `git-secrets`. Guessing at one is the only way this fails, so take it from
`{ring}`, which lists every adopted bundle beside the path to its ring. Use
`/list-bundles` if you do not have a name at all.

**What you get.** Anything the bundle says applies throughout it, to read now;
then every rule it holds, with what fires each, and a line naming anything that
reaches you by another route. **Bodies are not included** — open the ones that
match the work, and not the rest.

**If the path does not exist**, the bundle is not adopted here. That is an
answer, not an error.
""",
    }


def _names(bundles: list[Bundle]) -> tuple[dict[str, Doc], list[str]]:
    """Assign a skill name to every workflow, and report what collided.

    A bare slug is what an agent matches against, so it is worth keeping. Two
    bundles may legitimately both publish `audit-bundle`, and the loser of a
    silent collision would simply never be reachable — so a collision renames
    **both** sides rather than letting first-seen win.
    """
    claims: dict[str, list[Doc]] = {}
    for bundle in bundles:
        for doc in bundle.of_type("workflow"):
            # **The two navigation skills are reserved.** They are the floor —
            # the one route that works when nothing notices — so a workflow
            # that happened to be called `load-bundle` must not be able to
            # replace one silently. It is renamed instead, exactly as it would
            # be against another workflow.
            slug = f"{SLUG.sub('-', doc.bundle.replace('/', '-').lower())}-{doc.slug}" \
                if doc.slug in NAVIGATION else doc.slug
            claims.setdefault(slug, []).append(doc)

    chosen: dict[str, Doc] = {}
    collided: list[str] = []
    for slug, docs in claims.items():
        if len(docs) == 1:
            chosen[slug] = docs[0]
            continue
        collided.append(slug)
        for doc in docs:
            prefix = SLUG.sub("-", doc.bundle.replace("/", "-").lower())
            chosen[f"{prefix}-{slug}"] = doc
    return chosen, sorted(collided)


# --------------------------------------------------------------------------
# the project ring, and the adapter that fires it


def _adapter(bundles: list[Bundle], project_root: Path) -> str:
    """The block in `CLAUDE.md`, which carries no knowledge of its own.

    **It points at the project ring and gets out of the way.** Everything it
    could say about what this project knows is said in the ring, and a fact
    stated in two places is a fact that will disagree with itself.

    The one thing it does carry is the `@` imports for always-on content, and
    that is a path question rather than a design one: `@` resolves against the
    file it appears in, so imports written here reach the repository root while
    the same lines written into the ring would not.
    """
    ring = (ENTRYPOINT.relative_to(project_root).as_posix()
            if ENTRYPOINT.is_absolute()
            else ENTRYPOINT.as_posix())
    lines = [
        BEGIN,
        "",
        "## Knowledge this project has adopted",
        "",
        f"**Read `{ring}` now.** It lists what this project knows, what each "
        "part is for, and what brings it into play. Nothing below repeats it.",
        "",
        f"@{ring}",
        "",
    ]

    # **Nothing from a bundle is hoisted here, and that is the change.** A
    # Document declaring `matches: always` used to be imported into every
    # session by every adopting project — so a rule holding throughout one
    # bundle was charged to work that never touched it. It is scoped to its own
    # ring now and arrives when the bundle does.
    #
    # What belongs here is whatever is `always` for the *project*, and nothing
    # can declare that yet: every Document lives in a bundle, so every `always`
    # is bundle-scoped by construction. Left empty deliberately rather than
    # filled by pretending a bundle's claim is the project's.

    lines += [
        "Generated by `luma-foreman apply`. Edits between the markers are lost; "
        "everything outside them is yours.",
        "",
        END,
    ]
    return "\n".join(lines)


def ring_path(bundle_id: str) -> Path:
    """Where a bundle's own ring is written.

    **Never inside the vendored copy.** ``adoption.checksum`` covers every file
    under a bundle's root, so a generated file placed there would report the
    bundle as edited — the drift check cannot tell our writing from somebody
    else's. Rings live beside the bundles rather than within them.

    ``rings/`` cannot be mistaken for a namespace: ``adoption.discover`` finds a
    bundle by its ``BUNDLE.md``, and nothing here has one.
    """
    return Path(".luma/bundles/rings") / f"{bundle_id}.md"


def _entrypoint(bundles: list[Bundle], project_root: Path) -> str:
    """`1-project`: what this repository knows, one line per bundle.

    **A ring's map names the members of the next ring in**, and the members of
    `2-bundle` are bundles — so this names bundles and stops. What is inside one
    is that bundle's own ring to answer, which is what keeps standing cost
    per-bundle instead of per-document.
    """
    lines = [
        "<!-- Generated by `luma-foreman apply`. Edits are lost. -->",
        "",
        "# What this project knows",
        "",
        "**One line per bundle, and nothing about what is inside one.** Open a "
        "bundle's ring when its line matches the work, and not before — the "
        "ring says what the bundle holds and what brings each part into play.",
        "",
        "Everything here is vendored under `.luma/bundles/` and is part of this "
        "repository. It is a copy: change it upstream and take it again, never "
        "in place.",
        "",
    ]

    # **Nothing adopted is a true thing to say, and the most useful one.** An
    # agent arriving cold learns that this project knows nothing yet and what
    # would change that — which beats an empty heading it has to interpret.
    if not bundles:
        return "\n".join(lines[:4] + [
            "**Nothing is adopted yet.** This project has taken no bundles, so "
            "there is nothing here to open.",
            "",
            "    luma-foreman catalog show <catalog>   what is available",
            "    luma-foreman get <bundle>             take one",
            "    luma-foreman apply                    rewrite this file",
            "",
        ])

    for bundle in bundles:
        ring = ring_path(bundle.bundle_id).as_posix()
        version = f" {bundle.version}" if bundle.version else ""
        lines.append(f"- **`{bundle.bundle_id}`**{version} — "
                     f"{bundle.description or 'no description'}")
        lines.append(f"  - ring: `{ring}`")
    lines.append("")

    lines += [
        "Every workflow in these bundles is installed as a skill and can be "
        "invoked by name. They are not named here or in a bundle's ring, "
        "because this harness already loads their names and descriptions.",
        "",
    ]
    return "\n".join(lines)


def _bundle_ring(bundle: Bundle, project_root: Path) -> str:
    """`2-bundle`: what one bundle holds, and what fires each part.

    **Paths, never `@`.** A ring is the same artifact whatever reads it, and
    `@` is one harness's import syntax — the adapter is where harness-specific
    delivery belongs. A reader that has opened this ring can open a path.

    **This is where a bundle's `always` lands, and that is the change.** It used
    to be imported into every session by every adopting project, so a rule that
    holds throughout one bundle was charged to work that never touched it.
    Scoped here, it arrives when the bundle does.
    """
    home = bundle.root.relative_to(project_root).as_posix()
    lines = [
        "<!-- Generated by `luma-foreman apply`. Edits are lost. -->",
        "",
        f"# `{bundle.bundle_id}`" + (f" {bundle.version}" if bundle.version else ""),
        "",
    ]
    if bundle.description:
        lines += [bundle.description, ""]

    # **The bundle's own answer to where to start, which nothing read until
    # now.** Twenty of the catalog's bundles declare `entrypoint` and it reached
    # no reader — a declared field nobody consumes, which is the same defect as
    # a rule nobody can see. It is a claim about reading order and nothing more,
    # so it earns a line at the top rather than a delivery of its own.
    entry = bundle.entrypoint
    if entry and any(d.doc_id == entry for d in bundle.docs):
        # Named without its description, because the list below carries that and
        # a ring is fifteen lines long — saying the same sentence twice in one is
        # the sort of thing an author does not notice and a reader cannot miss.
        lines += [f"**Start at `{entry}`.**", ""]

    always = bundle.of_class("always-on")
    if always:
        lines += [
            "**Read these now.** Each declares `matches: always`, so nothing "
            "gates when it governs — which means everything done with this "
            "bundle.",
            "",
        ]
        for doc in sorted(always, key=lambda d: d.doc_id):
            rel = doc.path.relative_to(project_root).as_posix()
            lines.append(f"- `{rel}` — {doc.description or doc.title}".rstrip(" —"))
        lines.append("")

    # **Anything that acts on a consumer gets its line, whatever its class.**
    # Existence is cheap and content is expensive. A policy that matches nothing
    # lands in on-demand, and a rule nobody can see governs nothing — listing
    # only the advertised ones would turn a cost saving into the silent absence
    # this whole design exists to end.
    #
    # Two deliberate exceptions. **Background** is left out on the format's own
    # reasoning (§10.7): it does not act, and it is reached *through* the things
    # that do. **Workflows** are left out because this harness already loads
    # every skill's name and description at startup, and an adapter must not
    # render what its harness already carries.
    shown = [d for d in bundle.docs
             if d.type != "workflow"
             and d.klass != "always-on"
             and (d.klass == "advertised"
                  or (d.klass == "on-demand" and d.type == "policy"))]
    # **Say what is not here, or the count is a lie.** A ring claims to say what a
    # bundle holds. `git-secrets` holds five Documents, this named two, and the
    # sentence explaining the other three lived only in the project ring — which
    # a reader arriving by `/load-bundle` never opened. Reachable and invisible
    # is the failure the whole design exists to end, and it was in the artifact
    # built to end it.
    workflows = bundle.of_type("workflow")
    if workflows:
        names = ", ".join(f"`{w.slug}`" for w in sorted(workflows, key=lambda d: d.slug))
        lines += [
            f"**{len(workflows)} workflow(s) here reach you as skills, not through "
            f"this ring** — invoke by name: {names}.",
            "",
        ]

    if shown:
        lines += [f"In `{home}/`:", ""]
        for doc in sorted(shown, key=lambda d: (d.type, d.doc_id)):
            note = doc.description or doc.title or ""
            when = ", ".join(doc.matches)
            teeth = " **[blocked]**" if doc.on_violation == "block" else ""
            lines.append(f"- `{doc.doc_id}` ({doc.type}){teeth} — {note}".rstrip(" —"))
            if when:
                lines.append(f"  - matches: {when}")
        lines.append("")
    elif not always and not workflows:
        lines += [f"Nothing here is named separately. In `{home}/`.", ""]

    return "\n".join(lines)


def _splice(existing: str, block: str) -> str:
    """Put *block* into *existing*, touching nothing outside the markers.

    A project's `CLAUDE.md` is mostly hand-written and belongs to whoever wrote
    it. Owning a delimited region of it is the most that can be taken without
    destroying somebody's work, and it is enough.
    """
    start = existing.find(BEGIN_MARK)
    end = existing.find(END)
    if start != -1 and end != -1 and end > start:
        return existing[:start] + block + existing[end + len(END) :]
    if not existing.strip():
        return block + "\n"
    return existing.rstrip("\n") + "\n\n" + block + "\n"


# --------------------------------------------------------------------------
# the routing table


def _toml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _routing(bundles: list[Bundle], project_root: Path) -> str:
    """Every Document with a trigger: when it fires, and what happens then.

    **Compiled once and read by everything**, which is what keeps the gate and a
    future router from drifting apart. `on_violation` is one column of this
    table rather than a table of its own — blocking is simply its first
    consumer.

    It must be compiled rather than derived live: the gate runs before **every**
    tool call against a budget measured in milliseconds, and walking
    `.luma/bundles/` to parse frontmatter per call would spend it several times
    over.
    """
    lines = [
        "# Generated by `luma-foreman apply`. Edits are lost.",
        "#",
        "# Every Document that says when it applies, and what happens when it is",
        "# not complied with. The permission gate reads the rows that block; it",
        "# cannot be told to ignore them, and nothing in `agent-permissions`",
        "# writes here.",
        "",
    ]
    for bundle in bundles:
        for doc in bundle.docs:
            if not doc.matches:
                continue
            rel = doc.path.relative_to(project_root).as_posix()
            lines += [
                "[[rule]]",
                f"bundle = {_toml_str(bundle.bundle_id)}",
                f"document = {_toml_str(doc.doc_id)}",
                f"title = {_toml_str(doc.title or doc.doc_id)}",
                f"path = {_toml_str(rel)}",
                f"on_violation = {_toml_str(doc.on_violation)}",
                "matches = ["
                + ", ".join(_toml_str(a) for a in doc.matches)
                + "]",
                "",
            ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# the command


def _gate_installed() -> bool:
    """Is the hook that would honour a `block` actually wired into the harness?

    Declaring blocking where nothing intercepts produces a rule that **reads as
    enforced and is not** — a guardrail in the index and a label in reality.
    That is the failure this design exists to remove, so it is worth a warning
    rather than a silent nothing.
    """
    try:
        from .agent_permissions import install

        return bool(install.wiring().get("hook_ok"))
    except Exception:
        return False


def _refusals(bundles: list[Bundle]) -> list[str]:
    """Declarations this build cannot honour. Each one stops the run.

    The alternative is silently doing the nearest thing that works — a rule
    asking to be blocked becoming a line of prose — which is a rule that is
    weaker than it says and nobody finding out.
    """
    out = []
    for bundle in bundles:
        for doc in bundle.docs:
            if doc.on_violation not in SUPPORTED_ON_VIOLATION:
                out.append(
                    f"{bundle.bundle_id} {doc.doc_id}: on_violation "
                    f"'{doc.on_violation}' is not implemented"
                )
    return out


def _notices(bundles: list[Bundle], project_root: Path) -> list[str]:
    """Things worth saying that are not worth stopping for."""
    out = []
    for bundle in bundles:
        for doc in bundle.docs:
            # `preload` is read only so it can be reported. Honouring it would
            # let a half-migrated bundle behave correctly and stall there
            # forever, which is the one outcome a migration cannot survive.
            if doc.legacy_preload:
                out.append(
                    f"{bundle.bundle_id} {doc.doc_id}: still declares "
                    f"preload — say what surfaces it with matches, or nothing"
                )
            # A glob matching nothing never fires, and silence is
            # indistinguishable from a rule that has simply not come up. Saying
            # so is the difference between *does not apply* and *will never be
            # seen*.
            for trigger in doc.matches:
                kind, _, value = trigger.partition(":")
                if kind != "path" or not value:
                    continue
                try:
                    if next(project_root.glob(value), None) is None:
                        out.append(
                            f"{bundle.bundle_id} {doc.doc_id}: nothing in this "
                            f"project matches '{value}' — the rule can never fire"
                        )
                except (ValueError, OSError):
                    continue
    return out


def _explain(bundles: list[Bundle]) -> None:
    """The derivation, per Document, with its input beside its outcome.

    **The class names live here and nowhere else that matters.** `always-on`,
    `advertised` and `on-demand` are not vocabulary an author has to learn
    before writing anything — they are a derived column, printed next to what
    produced it, so the rule is visible rather than memorised. A lookup table
    nobody has to hold in their head is a different thing from a glossary.
    """
    docs = sorted((d for b in bundles for d in b.docs),
                  key=lambda d: (d.bundle, d.doc_id))
    if not docs:
        return
    width = min(max((len(d.doc_id) for d in docs), default=0), 44)
    print()
    print(f"  {'document':<{width}}  {'matches':<26}  derives to")
    print(f"  {'-' * width}  {'-' * 26}  {'-' * 10}")
    for doc in docs:
        kinds = dict.fromkeys(m.partition(":")[0] for m in doc.matches)
        shown = ", ".join(kinds)
        print(f"  {doc.doc_id[:width]:<{width}}  {(shown or '—')[:26]:<26}  {doc.klass}")
    print()
    print("  A Document that matches nothing is not lost — its name and line are")
    print("  in the index above. Only its body waits to be asked for.")


def run(project_root: Path, check: bool, explain: bool = False) -> int:
    bundles = discover(project_root)

    # **An empty project is a state, not an error.** It used to exit 2, which
    # made the one case that has to be correct the one case never exercised:
    # a repository that has adopted nothing still needs an adapter, and a
    # repository whose last bundle just left still needs its rings swept. Both
    # go through here, so both are wrong if this refuses.

    refused = _refusals(bundles)
    if refused:
        print("cannot project — declarations this build cannot honour:", file=sys.stderr)
        for line in refused:
            print(f"  {line}", file=sys.stderr)
        return 2

    planned: dict[Path, str] = {}
    chosen, collided = _names(bundles)
    skills = project_root / ".claude" / "skills"
    for name, doc in chosen.items():
        bundle = next(b for b in bundles if b.bundle_id == doc.bundle)
        planned[skills / name / "SKILL.md"] = _skill(doc, bundle, project_root)
    for name, body in _navigation(bundles).items():
        planned[skills / name / "SKILL.md"] = body

    routing = adoption.bundles_dir(project_root) / "routing.toml"
    planned[routing] = _routing(bundles, project_root)

    planned[project_root / ENTRYPOINT] = _entrypoint(bundles, project_root)
    for bundle in bundles:
        planned[project_root / ring_path(bundle.bundle_id)] = _bundle_ring(
            bundle, project_root)

    claude = project_root / "CLAUDE.md"
    current = claude.read_text(encoding="utf-8") if claude.is_file() else ""
    planned[claude] = _splice(current, _adapter(bundles, project_root))

    kept = set(chosen) | set(NAVIGATION)
    stale = [p for p in _generated(skills).values() if p.name not in kept]

    # A ring for a bundle that left is worse than a missing one: it names
    # documents that are no longer on disk, and nothing about reading it says
    # so. Swept by the same rule as an orphaned skill.
    rings_root = project_root / ".luma" / "bundles" / "rings"
    orphan_rings = [
        r for r in sorted(rings_root.rglob("*.md"))
        if (project_root / ring_path(
            r.relative_to(rings_root).with_suffix("").as_posix())) not in planned
    ] if rings_root.is_dir() else []
    changed = [
        path
        for path, content in planned.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]

    if check:
        for path in sorted(changed):
            print(f"stale: {path.relative_to(project_root).as_posix()}")
        for path in sorted(stale) + orphan_rings:
            print(f"orphan: {path.relative_to(project_root).as_posix()}")
        if changed or stale or orphan_rings:
            print("\nrun `luma-foreman apply`")
            return 1
        print("up to date")
        return 0

    for path, content in planned.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    for path in stale:
        shutil.rmtree(path)
    for path in orphan_rings:
        path.unlink()
        # An empty namespace directory left behind is a question a reader has to
        # answer. Walk up while each parent is empty and still inside rings/.
        parent = path.parent
        while parent != rings_root and parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent

    workflows = sum(len(b.of_type("workflow")) for b in bundles)
    counts = {k: sum(len(b.of_class(k)) for b in bundles)
              for k in ("always-on", "advertised", "on-demand")}
    print(f"{len(bundles)} bundle(s) written out")
    print(f"  skills     {workflows} workflow(s) + {len(NAVIGATION)} navigation "
          f"-> .claude/skills/")
    print(f"  rings      1 project + {len(bundles)} bundle(s) -> .luma/bundles/")
    print(f"  always-on  {counts['always-on']} read when their own bundle's ring opens")
    print(f"  advertised {counts['advertised']} named, opened when they match")
    print(f"  on-demand  {counts['on-demand']} reachable, not announced")
    if explain:
        _explain(bundles)

    blocking = [d for b in bundles for d in b.docs if d.on_violation == "block"]
    if blocking and not _gate_installed():
        print()
        print(
            f"  WARNING  {len(blocking)} rule(s) declare blocking and nothing here "
            f"enforces them.\n"
            f"           The permission gate is not wired into this harness, so a "
            f"rule that\n"
            f"           reads as a guardrail is a label. Install it:\n"
            f"             luma-foreman agent-permissions install"
        )

    for line in _notices(bundles, project_root):
        print(f"  notice   {line}")
    if stale:
        print(f"  removed  {len(stale)} skill(s) for bundles no longer here")
    if orphan_rings:
        print(f"  removed  {len(orphan_rings)} ring(s) for bundles no longer here")
    if collided:
        print()
        print(
            "  note: these workflow names appear in more than one bundle and "
            "were\n        prefixed on both sides so neither is unreachable: "
            + ", ".join(collided)
        )
    if not changed and not stale and not orphan_rings:
        print("\n  (nothing changed)")
    else:
        print("\n  Commit the result, or gitignore .claude/ — it is generated either way.")
    return 0


def main(argv: list[str]) -> int:
    check = False
    explain = False
    target: Path | None = None
    rest = list(argv)
    while rest:
        arg = rest.pop(0)
        if arg in ("-h", "--help"):
            print(USAGE)
            return 0
        if arg == "--check":
            check = True
        elif arg == "--explain":
            explain = True
        elif arg == "--to":
            if not rest:
                print("luma-foreman apply: --to needs a directory", file=sys.stderr)
                return 2
            target = Path(rest.pop(0))
        else:
            print(f"luma-foreman apply: unknown option: {arg}", file=sys.stderr)
            return 2

    if target and not target.is_dir():
        print(f"luma-foreman apply: not a directory: {target}", file=sys.stderr)
        return 2
    project_root, _ = project.resolve(target or Path.cwd())
    return run(project_root, check, explain)
