"""Render a Bundle's ``INDEX.md`` — the generated map a reader opens first.

**An index is a rendering, and the frontmatter it renders is authoritative**
(LKF v0.0.19, *Reserved files*). This module derives everything from the
Documents' own frontmatter and ``BUNDLE.md``; nothing here is a second
source of truth, and ``--check`` is regenerate-and-compare, which is why it
cannot disagree with the generator.

**Generation is an authoring act.** It runs where a bundle is written —
never against a vendored copy in an adopting project, whose ``INDEX.md``
arrived frozen at its version and is covered by the adoption checksum. The
command refuses that case rather than trusting the operator to remember it.

The rendered shape is the bundle design MVP's mock-up: purpose, the
authored body of ``BUNDLE.md``, then the three loading postures as visible
groupings — Required (``matches: eager``), Offered (conditions), By request
(nothing volunteers it) — and one class-level sentence accounting for
procedures, which surface through harness registration and are never
listed (their names and descriptions are already paid for there).
"""

from __future__ import annotations

import sys
from pathlib import Path

from . import lkf

MARKER = "<!-- Generated by `luma-foreman bundle index`. Regenerate, never edit. -->"

REQUIRED = "## Required — do NOT act on this bundle before reading these"
OFFERED = "## Offered — open when the work matches"
BY_REQUEST = "## By request — reached by name or by citation"

KEYWORDS = ("eager", "nothing")


def _documents(root: Path) -> list[tuple[str, dict[str, str], tuple[str, ...]]]:
    """Every Document in the bundle: (id, frontmatter, matches entries).

    ``BUNDLE.md`` speaks for the bundle rather than being a member,
    ``INDEX.md`` is this module's own output, templates are material rather
    than knowledge, and a file with no frontmatter is an Asset. All four are
    excluded rather than listed as things nobody can act on.
    """
    out = []
    if not root.is_dir():
        return out
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(root).as_posix()
        if rel in ("BUNDLE.md", "INDEX.md") or rel.startswith("templates/"):
            continue
        keys = lkf.read(path)
        if keys is None:
            continue
        out.append((rel.removesuffix(".md"), keys, lkf.matches(path)))
    return out


def _entry(doc_id: str, keys: dict[str, str]) -> str:
    kind = lkf.unquote(keys.get("type", "")) or "document"
    description = lkf.unquote(keys.get("description", ""))
    line = f"- `{doc_id}` ({kind})"
    return f"{line} — {description}" if description else line


def _body(root: Path) -> str:
    """The authored half: BUNDLE.md's body, minus its heading.

    The generator supplies the H1 from the bundle's own metadata, so a
    second one from the body would say the same thing twice.
    """
    try:
        text = (root / "BUNDLE.md").read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""
    _, body = lkf.split(text)
    lines = body.strip().splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
    return "\n".join(lines).strip()


def render(root: Path, warn=None) -> str:
    """The index content for one bundle, derived and deterministic."""
    warn = warn or (lambda message: print(f"luma-foreman bundle index: {message}", file=sys.stderr))
    bundle = lkf.read(root / "BUNDLE.md") or {}
    title = lkf.unquote(bundle.get("title", "")) or root.name
    version = lkf.unquote(bundle.get("version", ""))
    description = lkf.unquote(bundle.get("description", ""))
    if not description:
        warn(f"{root}: BUNDLE.md has no description — the index opens with nothing")

    required: list[str] = []
    offered: list[str] = []
    by_request: list[str] = []
    procedure_dirs: set[str] = set()

    for doc_id, keys, entries in _documents(root):
        if lkf.unquote(keys.get("type", "")) == "procedure":
            procedure_dirs.add(doc_id.split("/", 1)[0] if "/" in doc_id else "")
            continue
        if entries == ("eager",):
            required.append(f"{_entry(doc_id, keys)}\n  - matches: eager")
        elif entries and all(":" in e for e in entries):
            rendered = ", ".join(entries)
            offered.append(f"{_entry(doc_id, keys)}\n  - matches: {rendered}")
        else:
            keyword = entries[0] if entries else None
            if keyword and keyword not in KEYWORDS:
                warn(f"{doc_id}: unknown matches keyword '{keyword}' — treated as nothing")
            by_request.append(_entry(doc_id, keys))

    parts: list[str] = [MARKER, "", f"# {title} {version}".rstrip()]
    if description:
        parts += ["", description]
    body = _body(root)
    if body:
        parts += ["", body]
    for heading, entries_ in ((REQUIRED, required), (OFFERED, offered), (BY_REQUEST, by_request)):
        if entries_:
            parts += ["", heading, ""] + entries_
    if procedure_dirs:
        where = procedure_dirs.pop() if len(procedure_dirs) == 1 and "" not in procedure_dirs else ""
        place = f"in `{where}/` " if where else "here "
        parts += ["", f"Procedures {place}are installed in your harness — invoke them by "
                      "name rather than reading them here."]
    return "\n".join(parts) + "\n"


def generate(root: Path) -> int:
    if not (root / "BUNDLE.md").is_file():
        print(f"luma-foreman bundle index: {root} has no BUNDLE.md — not a bundle", file=sys.stderr)
        return 2
    (root / "INDEX.md").write_text(render(root), encoding="utf-8")
    print(f"wrote {root / 'INDEX.md'}")
    return 0


def check(root: Path) -> int:
    """Regenerate-and-compare. Same state, same answer, every run."""
    target = root / "INDEX.md"
    if not target.is_file():
        print(f"{target}: missing — generate it", file=sys.stderr)
        return 1
    expected = render(root, warn=lambda _: None)
    try:
        actual = target.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        print(f"{target}: unreadable", file=sys.stderr)
        return 1
    if actual == expected:
        print(f"{target}: current")
        return 0
    print(f"{target}: disagrees with the frontmatter it renders — regenerate", file=sys.stderr)
    return 1


def vendored_here(root: Path) -> str | None:
    """The adopted-bundle ID when *root* is a vendored copy, else None.

    A vendored copy's index is frozen at its version; regenerating it here
    would be editing an adopted bundle, which is drift wearing a helpful
    face. Detection keys on the receipt, not the path alone: a local bundle
    also lives under ``.luma/bundles/`` and is exactly what this command is
    for.
    """
    from . import adoption

    resolved = root.resolve()
    for parent in resolved.parents:
        if parent.name == "bundles" and parent.parent.name == ".luma":
            project = parent.parent.parent
            bundle_id = resolved.relative_to(parent).as_posix()
            entry = adoption.read(project).get(bundle_id)
            if entry is not None and entry.source:
                return bundle_id
            return None
    return None


def main(argv: list[str]) -> int:
    do_check = False
    paths: list[str] = []
    for arg in argv:
        if arg == "--check":
            do_check = True
        elif arg in ("-h", "--help"):
            print("usage: luma-foreman bundle index <bundle-dir> [--check]")
            return 0
        else:
            paths.append(arg)
    if len(paths) != 1:
        print("usage: luma-foreman bundle index <bundle-dir> [--check]", file=sys.stderr)
        return 2
    root = Path(paths[0])
    if not root.is_dir():
        print(f"luma-foreman bundle index: not a directory: {root}", file=sys.stderr)
        return 2
    adopted = vendored_here(root)
    if adopted:
        print(
            f"luma-foreman bundle index: {adopted} is a vendored copy — its index is "
            "frozen at the adopted version. Regenerate it upstream and take the bundle again.",
            file=sys.stderr,
        )
        return 2
    return check(root) if do_check else generate(root)
