"""Projecting what a project adopted into what its harness actually reads.

**Adoption puts knowledge in the repository; nothing yet puts it in front of an
agent.** A bundle in `.luma/bundles/` is inert until something tells Claude Code
that it exists, and telling it is harness-specific work that the bundle must not
have to know about.

**Thin adapters, and thin is the whole design.** What gets written is a pointer
and a reason to follow it — never a copy of the document. A copy would be a
second source of truth that drifts from the first, and it would charge every
session for content that was supposed to load only when the work matched.

Two projections, because a harness has two ways in:

| | |
| --- | --- |
| **skills** | one per `workflow`, so an agent can be *asked* to do the thing |
| **the index** | one block in `CLAUDE.md`, so an agent knows what exists without being told where to look |

**The index is the part that closes the gap.** Everything else assumes somebody
already knows the knowledge is there. `an-index-of-what-exists` is the policy it
implements: make existence cheap and content expensive, so a consumer can always
see what it is *not* loading.

Everything written here is generated and disposable. The source is `.luma/`.
"""

from __future__ import annotations

import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from . import adoption, lkf, project

USAGE = """Project adopted bundles into what this project's harness reads.

  luma-foreman outfit             write the adapters and the index
  luma-foreman outfit --check     report what would change, write nothing
  luma-foreman outfit --to <dir>  a project other than this repository

Writes .claude/skills/<name>/SKILL.md for every workflow, and a managed block in
CLAUDE.md listing everything adopted. Both are generated from .luma/ and are
disposable — regenerate them rather than editing them.

Exit codes: 0 written (or up to date), 1 --check found staleness, 2 could not run."""

# Written into every generated file. It is what makes a later run able to tell
# what it owns from what somebody wrote by hand, which is what lets a skill for
# an un-adopted bundle actually leave.
MARK = "luma-foreman:generated"

BEGIN = "<!-- luma:begin — generated by `luma-foreman outfit`. Edits between these markers are lost. -->"
END = "<!-- luma:end -->"

# `_types/` holds contracts, not reading material — a Type Definition is
# consulted when writing a document of that type, which is a job the workflow
# already sends you to. Listing them would double the index to say nothing.
SKIP = ("_types",)

SLUG = re.compile(r"[^a-z0-9-]+")


@dataclass(frozen=True)
class Doc:
    """A Document inside a vendored bundle, as the projection needs it."""

    bundle: str
    doc_id: str
    path: Path
    type: str
    title: str
    description: str
    preload: str

    @property
    def slug(self) -> str:
        return SLUG.sub("-", self.doc_id.rsplit("/", 1)[-1].lower()).strip("-")


@dataclass(frozen=True)
class Bundle:
    """A vendored bundle and the Documents worth projecting."""

    bundle_id: str
    root: Path
    version: str
    description: str
    docs: tuple[Doc, ...]

    def of_type(self, kind: str) -> list[Doc]:
        return [d for d in self.docs if d.type == kind]

    def standing(self) -> list[Doc]:
        """Documents this bundle expects to be loaded before work starts."""
        return [d for d in self.docs if d.preload in ("mandatory", "recommended")]


def _text(keys: dict[str, str], name: str) -> str:
    return lkf.unquote(keys.get(name, "")).strip()


def discover(project_root: Path) -> list[Bundle]:
    """Every bundle in `.luma/bundles/`, adopted or written here.

    Both are projected. What a project wrote for itself is as much a part of how
    it works as what it took from a catalog, and an agent has no reason to care
    which is which — that distinction matters to drift checking, not to loading.
    """
    root = adoption.bundles_dir(project_root)
    if not root.is_dir():
        return []

    out: list[Bundle] = []
    for manifest in sorted(root.glob("*/*/bundle.md")):
        home = manifest.parent
        bundle_id = home.relative_to(root).as_posix()
        keys = lkf.read(manifest) or {}

        docs: list[Doc] = []
        for path in sorted(home.rglob("*.md")):
            rel = path.relative_to(home)
            if rel.parts[0] in SKIP or rel.as_posix() == "bundle.md":
                continue
            front = lkf.read(path)
            if front is None or "type" not in front:
                continue  # an Asset — a template, an example. Not addressable.
            docs.append(
                Doc(
                    bundle=bundle_id,
                    doc_id=rel.as_posix()[:-3],
                    path=path,
                    type=_text(front, "type"),
                    title=_text(front, "title"),
                    description=_text(front, "description"),
                    preload=_text(front, "preload") or "optional",
                )
            )

        out.append(
            Bundle(
                bundle_id=bundle_id,
                root=home,
                version=_text(keys, "version"),
                description=_text(keys, "description"),
                docs=tuple(docs),
            )
        )
    return out


# --------------------------------------------------------------------------
# skills


def _skill(doc: Doc, bundle: Bundle, project_root: Path) -> str:
    """One adapter: harness frontmatter, and where the real document is."""
    source = doc.path.relative_to(project_root).as_posix()
    lines = [
        "---",
        f"name: {doc.slug}",
        f"description: {doc.description}",
        "---",
        "",
        f"<!-- {MARK} from {bundle.bundle_id} {doc.doc_id}. "
        f"Regenerate with `luma-foreman outfit`; edits are lost. -->",
        "",
        f"# {doc.title or doc.slug}",
        "",
        f"**Read `{source}` and follow it.** That file is the workflow. This is "
        f"the adapter that makes it reachable from here, and it deliberately "
        f"carries no copy of it — the copy would drift.",
    ]

    standing = [d for d in bundle.standing() if d.doc_id != doc.doc_id]
    if standing:
        lines += ["", "Standing context this workflow assumes:", ""]
        for d in standing:
            rel = d.path.relative_to(project_root).as_posix()
            lines.append(f"- `{rel}` — {d.description or d.title or d.doc_id}")

    lines += [
        "",
        f"From the `{bundle.bundle_id}` bundle, vendored at "
        f"`{bundle.root.relative_to(project_root).as_posix()}/`. Do not edit "
        f"anything under there — an adopted bundle is a copy, and editing it is "
        f"drift.",
        "",
    ]
    return "\n".join(lines)


def _generated(skills: Path) -> dict[str, Path]:
    """Skill directories a previous run wrote, keyed by name."""
    if not skills.is_dir():
        return {}
    out = {}
    for path in sorted(skills.glob("*/SKILL.md")):
        try:
            if MARK in path.read_text(encoding="utf-8"):
                out[path.parent.name] = path.parent
        except (OSError, UnicodeDecodeError):
            continue
    return out


def _names(bundles: list[Bundle]) -> tuple[dict[str, Doc], list[str]]:
    """Assign a skill name to every workflow, and report what collided.

    A bare slug is what an agent matches against, so it is worth keeping. Two
    bundles may legitimately both publish `audit-bundle`, and the loser of a
    silent collision would simply never be reachable — so a collision renames
    **both** sides rather than letting first-seen win.
    """
    claims: dict[str, list[Doc]] = {}
    for bundle in bundles:
        for doc in bundle.of_type("workflow"):
            claims.setdefault(doc.slug, []).append(doc)

    chosen: dict[str, Doc] = {}
    collided: list[str] = []
    for slug, docs in claims.items():
        if len(docs) == 1:
            chosen[slug] = docs[0]
            continue
        collided.append(slug)
        for doc in docs:
            prefix = SLUG.sub("-", doc.bundle.replace("/", "-").lower())
            chosen[f"{prefix}-{slug}"] = doc
    return chosen, sorted(collided)


# --------------------------------------------------------------------------
# the index


def _index(bundles: list[Bundle], project_root: Path) -> str:
    lines = [
        BEGIN,
        "",
        "## Knowledge this project has adopted",
        "",
        "Everything below is vendored under `.luma/bundles/` and is part of this "
        "repository. **This list is the index, not the content** — open a "
        "document when the work matches its line, and do not load the rest.",
        "",
    ]

    # Hoisted rather than left bold inside each bundle's list. Across several
    # bundles the mandatory ones would otherwise be scattered through the block,
    # and the one thing a reader must not have to assemble for themselves is the
    # list of what they were required to read.
    required = [d for b in bundles for d in b.docs if d.preload == "mandatory"]
    if required:
        lines += [
            "**Read these before working here.** Their bundles declare them "
            "`preload: mandatory`, which is the strongest claim a bundle can "
            "make on a reader's attention.",
            "",
        ]
        for doc in required:
            rel = doc.path.relative_to(project_root).as_posix()
            lines.append(f"- `{rel}` — {doc.description or doc.title or ''}".rstrip())
        lines.append("")

    for bundle in bundles:
        home = bundle.root.relative_to(project_root).as_posix()
        heading = f"### `{bundle.bundle_id}`"
        if bundle.version:
            heading += f" {bundle.version}"
        lines += [heading, ""]
        if bundle.description:
            lines += [bundle.description, ""]
        lines += [f"In `{home}/`:", ""]

        for doc in sorted(bundle.docs, key=lambda d: (d.type, d.doc_id)):
            note = doc.description or doc.title or ""
            flag = " **[read first]**" if doc.preload == "mandatory" else ""
            lines.append(
                f"- `{doc.doc_id}.md` ({doc.type}){flag} — {note}".rstrip(" —")
            )
        lines.append("")

    lines += [
        "Workflows here are also installed as skills, so they can be invoked by "
        "name. Everything under `.luma/bundles/` is a copy — change it upstream "
        "and re-adopt, never in place.",
        "",
        END,
    ]
    return "\n".join(lines)


def _splice(existing: str, block: str) -> str:
    """Put *block* into *existing*, touching nothing outside the markers.

    A project's `CLAUDE.md` is mostly hand-written and belongs to whoever wrote
    it. Owning a delimited region of it is the most that can be taken without
    destroying somebody's work, and it is enough.
    """
    start = existing.find(BEGIN)
    end = existing.find(END)
    if start != -1 and end != -1 and end > start:
        return existing[:start] + block + existing[end + len(END) :]
    if not existing.strip():
        return block + "\n"
    return existing.rstrip("\n") + "\n\n" + block + "\n"


# --------------------------------------------------------------------------
# the command


def run(project_root: Path, check: bool) -> int:
    bundles = discover(project_root)
    if not bundles:
        print(
            "nothing adopted — .luma/bundles/ holds no bundles.\n"
            "  luma-foreman adopt --list --from <catalog>",
            file=sys.stderr,
        )
        return 2

    planned: dict[Path, str] = {}
    chosen, collided = _names(bundles)
    skills = project_root / ".claude" / "skills"
    for name, doc in chosen.items():
        bundle = next(b for b in bundles if b.bundle_id == doc.bundle)
        planned[skills / name / "SKILL.md"] = _skill(doc, bundle, project_root)

    claude = project_root / "CLAUDE.md"
    current = claude.read_text(encoding="utf-8") if claude.is_file() else ""
    planned[claude] = _splice(current, _index(bundles, project_root))

    stale = [p for p in _generated(skills).values() if p.name not in chosen]
    changed = [
        path
        for path, content in planned.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]

    if check:
        for path in sorted(changed):
            print(f"stale: {path.relative_to(project_root).as_posix()}")
        for path in sorted(stale):
            print(f"orphan: {path.relative_to(project_root).as_posix()}")
        if changed or stale:
            print("\nrun `luma-foreman outfit`")
            return 1
        print("up to date")
        return 0

    for path, content in planned.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    for path in stale:
        shutil.rmtree(path)

    workflows = sum(len(b.of_type("workflow")) for b in bundles)
    mandatory = sum(1 for b in bundles for d in b.docs if d.preload == "mandatory")
    print(f"{len(bundles)} bundle(s) projected")
    print(f"  skills   {workflows} workflow(s) -> .claude/skills/")
    print(f"  index    {sum(len(b.docs) for b in bundles)} document(s) -> CLAUDE.md")
    print(f"           {mandatory} marked read-before-working")
    if stale:
        print(f"  removed  {len(stale)} skill(s) for bundles no longer here")
    if collided:
        print()
        print(
            "  note: these workflow names appear in more than one bundle and "
            "were\n        prefixed on both sides so neither is unreachable: "
            + ", ".join(collided)
        )
    if not changed and not stale:
        print("\n  (nothing changed)")
    else:
        print("\n  Commit the result, or gitignore .claude/ — it is generated either way.")
    return 0


def main(argv: list[str]) -> int:
    check = False
    target: Path | None = None
    rest = list(argv)
    while rest:
        arg = rest.pop(0)
        if arg in ("-h", "--help"):
            print(USAGE)
            return 0
        if arg == "--check":
            check = True
        elif arg == "--to":
            if not rest:
                print("luma-foreman outfit: --to needs a directory", file=sys.stderr)
                return 2
            target = Path(rest.pop(0))
        else:
            print(f"luma-foreman outfit: unknown option: {arg}", file=sys.stderr)
            return 2

    if target and not target.is_dir():
        print(f"luma-foreman outfit: not a directory: {target}", file=sys.stderr)
        return 2
    project_root, _ = project.resolve(target or Path.cwd())
    return run(project_root, check)
