"""Projecting what a project adopted into what its harness actually reads.

**Adoption puts knowledge in the repository; nothing yet puts it in front of an
agent.** A bundle in `.luma/bundles/` is inert until something tells Claude Code
that it exists, and telling it is harness-specific work that the bundle must not
have to know about.

**Thin adapters, and thin is the whole design.** What gets written is a pointer
and a reason to follow it — never a copy of the document. A copy would be a
second source of truth that drifts from the first, and it would charge every
session for content that was supposed to load only when the work matched.

Two projections, because a harness has two ways in:

| | |
| --- | --- |
| **skills** | one per `workflow`, so an agent can be *asked* to do the thing |
| **the index** | one block in `CLAUDE.md`, so an agent knows what exists without being told where to look |

**The index is the part that closes the gap.** Everything else assumes somebody
already knows the knowledge is there. `an-index-of-what-exists` is the policy it
implements: make existence cheap and content expensive, so a consumer can always
see what it is *not* loading.

Everything written here is generated and disposable. The source is `.luma/`.
"""

from __future__ import annotations

import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from . import adoption, lkf, project

USAGE = """Project adopted bundles into what this project's harness reads.

  luma-foreman outfit             write the adapters and the index
  luma-foreman outfit --check     report what would change, write nothing
  luma-foreman outfit --to <dir>  a project other than this repository

Writes .claude/skills/<name>/SKILL.md for every workflow, and a managed block in
CLAUDE.md listing everything adopted. Both are generated from .luma/ and are
disposable — regenerate them rather than editing them.

Exit codes: 0 written (or up to date), 1 --check found staleness, 2 could not run."""

# Written into every generated file. It is what makes a later run able to tell
# what it owns from what somebody wrote by hand, which is what lets a skill for
# an un-adopted bundle actually leave.
MARK = "luma-foreman:generated"

BEGIN = "<!-- luma:begin — generated by `luma-foreman outfit`. Edits between these markers are lost. -->"
END = "<!-- luma:end -->"

# `_types/` holds contracts, not reading material — a Type Definition is
# consulted when writing a document of that type, which is a job the workflow
# already sends you to. Listing them would double the index to say nothing.
SKIP = ("_types",)

SLUG = re.compile(r"[^a-z0-9-]+")

# What this build can actually do at the moment a rule is broken. The vocabulary
# is larger — `audit`, `warn`, `require_reason`, `require_approval` all mean
# something — and none of the rest is implemented. A declaration this cannot
# honour is refused rather than quietly downgraded to the nearest thing that
# works, because a rule that silently becomes weaker than it says is the exact
# failure the whole design exists to remove.
SUPPORTED_ON_VIOLATION = ("allow", "block")

# `README.md` is deliberately not an owner, whatever it contains. It carries
# universal permission semantics — everybody believes they may edit it freely —
# so a system that depends on its structure has a fuse in it, lit by the next
# person who tidies up.
NEVER_OWNS = ("README",)


def _owns_directory(path: Path) -> bool:
    """Is this the all-caps Document that its directory *is*?

    The casing is the signal rather than any particular word, so a workflow gets
    `WORKFLOW.md` and somebody's own type gets its own — nothing is centrally
    reserved, which the open type vocabulary requires.
    """
    stem = path.stem
    return stem.isupper() and stem not in NEVER_OWNS


@dataclass(frozen=True)
class Doc:
    """A Document inside a vendored bundle, as the projection needs it."""

    bundle: str
    doc_id: str
    path: Path
    type: str
    title: str
    description: str
    compliance: str
    on_violation: str
    applies_to: tuple[str, ...]
    legacy_preload: str = ""

    @property
    def slug(self) -> str:
        return SLUG.sub("-", self.doc_id.rsplit("/", 1)[-1].lower()).strip("-")

    @property
    def klass(self) -> str:
        """Where this lands: standing, advertised, or on-demand.

        Derived, never declared. **There is exactly one path to standing** — a
        policy that binds with no trigger anyone could state — so the expensive
        outcome is something an author falls into rather than selects, and it
        shows up as a gap in what was said rather than as a decision somebody
        made.
        """
        if self.applies_to:
            return "advertised"
        return "standing" if self.compliance == "required" else "on-demand"


@dataclass(frozen=True)
class Bundle:
    """A vendored bundle and the Documents worth projecting."""

    bundle_id: str
    root: Path
    version: str
    description: str
    docs: tuple[Doc, ...]

    def of_type(self, kind: str) -> list[Doc]:
        return [d for d in self.docs if d.type == kind]

    def of_class(self, klass: str) -> list[Doc]:
        return [d for d in self.docs if d.klass == klass]

    def standing(self) -> list[Doc]:
        """Documents whose bodies have to be present before work starts."""
        return self.of_class("standing")


def _text(keys: dict[str, str], name: str) -> str:
    return lkf.unquote(keys.get(name, "")).strip()


def discover(project_root: Path) -> list[Bundle]:
    """Every bundle in `.luma/bundles/`, adopted or written here.

    Both are projected. What a project wrote for itself is as much a part of how
    it works as what it took from a catalog, and an agent has no reason to care
    which is which — that distinction matters to drift checking, not to loading.
    """
    root = adoption.bundles_dir(project_root)
    if not root.is_dir():
        return []

    out: list[Bundle] = []
    for manifest in sorted(root.glob("*/*/BUNDLE.md")):
        home = manifest.parent
        bundle_id = home.relative_to(root).as_posix()
        keys = lkf.read(manifest) or {}

        # A directory that *is* a Document owns everything beneath it. Its
        # subordinates — a tutorial's steps, a template beside the workflow that
        # copies it — are reachable only through the owner and never announced
        # separately. That is the whole of subordination: no field, no
        # declaration, just where a file sits.
        owned: dict[Path, Path] = {}
        for path in sorted(home.rglob("*.md")):
            # The bundle's own manifest owns the bundle directory by exactly
            # this rule — and must not hide it. A bundle's members are its
            # content, which is the thing being projected; subordination
            # applies *within* a bundle, never at its root.
            if path.parent == home:
                continue
            if _owns_directory(path):
                owned[path.parent] = path

        def owner_of(path: Path) -> Path | None:
            for parent in path.parents:
                if parent in owned and owned[parent] != path:
                    return owned[parent]
                if parent == home:
                    break
            return None

        docs: list[Doc] = []
        for path in sorted(home.rglob("*.md")):
            rel = path.relative_to(home)
            if rel.parts[0] in SKIP or rel.as_posix() == "BUNDLE.md":
                continue
            if owner_of(path) is not None:
                continue  # subordinate: it arrives with its owner or not at all
            front = lkf.read(path)
            if front is None or "type" not in front:
                continue  # an Asset — a template, an example. Not addressable.

            # The directory is the identity. `WORKFLOW.md` is a local detail
            # nothing references, visible only to somebody already standing in
            # the directory — so the ID, the skill name and every link shorten
            # to the directory that holds it.
            doc_id = rel.parent.as_posix() if _owns_directory(path) else rel.as_posix()[:-3]

            docs.append(
                Doc(
                    bundle=bundle_id,
                    doc_id=doc_id,
                    path=path,
                    type=_text(front, "type"),
                    title=_text(front, "title"),
                    description=_text(front, "description"),
                    # A policy *is* an obligation, so it binds unless it says
                    # otherwise — absent means `required`. Nothing else carries
                    # compliance at all: a workflow's steps bind by being steps,
                    # and a concept obliges nothing by definition.
                    compliance=(
                        _text(front, "compliance")
                        or ("required" if _text(front, "type") == "policy" else "")
                    ),
                    on_violation=_text(front, "on_violation") or "allow",
                    applies_to=lkf.applies_to(path),
                    legacy_preload=_text(front, "preload"),
                )
            )

        out.append(
            Bundle(
                bundle_id=bundle_id,
                root=home,
                version=_text(keys, "version"),
                description=_text(keys, "description"),
                docs=tuple(docs),
            )
        )
    return out


# --------------------------------------------------------------------------
# skills


def _skill(doc: Doc, bundle: Bundle, project_root: Path) -> str:
    """One adapter: harness frontmatter, and where the real document is."""
    source = doc.path.relative_to(project_root).as_posix()
    lines = [
        "---",
        f"name: {doc.slug}",
        f"description: {doc.description}",
        "---",
        "",
        f"<!-- {MARK} from {bundle.bundle_id} {doc.doc_id}. "
        f"Regenerate with `luma-foreman outfit`; edits are lost. -->",
        "",
        f"# {doc.title or doc.slug}",
        "",
        f"**Read `{source}` and follow it.** That file is the workflow. This is "
        f"the adapter that makes it reachable from here, and it deliberately "
        f"carries no copy of it — the copy would drift.",
    ]

    standing = [d for d in bundle.standing() if d.doc_id != doc.doc_id]
    if standing:
        lines += ["", "Standing context this workflow assumes:", ""]
        for d in standing:
            rel = d.path.relative_to(project_root).as_posix()
            lines.append(f"- `{rel}` — {d.description or d.title or d.doc_id}")

    lines += [
        "",
        f"From the `{bundle.bundle_id}` bundle, vendored at "
        f"`{bundle.root.relative_to(project_root).as_posix()}/`. Do not edit "
        f"anything under there — an adopted bundle is a copy, and editing it is "
        f"drift.",
        "",
    ]
    return "\n".join(lines)


def _generated(skills: Path) -> dict[str, Path]:
    """Skill directories a previous run wrote, keyed by name."""
    if not skills.is_dir():
        return {}
    out = {}
    for path in sorted(skills.glob("*/SKILL.md")):
        try:
            if MARK in path.read_text(encoding="utf-8"):
                out[path.parent.name] = path.parent
        except (OSError, UnicodeDecodeError):
            continue
    return out


def _names(bundles: list[Bundle]) -> tuple[dict[str, Doc], list[str]]:
    """Assign a skill name to every workflow, and report what collided.

    A bare slug is what an agent matches against, so it is worth keeping. Two
    bundles may legitimately both publish `audit-bundle`, and the loser of a
    silent collision would simply never be reachable — so a collision renames
    **both** sides rather than letting first-seen win.
    """
    claims: dict[str, list[Doc]] = {}
    for bundle in bundles:
        for doc in bundle.of_type("workflow"):
            claims.setdefault(doc.slug, []).append(doc)

    chosen: dict[str, Doc] = {}
    collided: list[str] = []
    for slug, docs in claims.items():
        if len(docs) == 1:
            chosen[slug] = docs[0]
            continue
        collided.append(slug)
        for doc in docs:
            prefix = SLUG.sub("-", doc.bundle.replace("/", "-").lower())
            chosen[f"{prefix}-{slug}"] = doc
    return chosen, sorted(collided)


# --------------------------------------------------------------------------
# the index


def _index(bundles: list[Bundle], project_root: Path) -> str:
    """The standing surface: what is delivered, and what merely exists.

    Three classes, and the difference between the first two is the whole point.
    A **standing** Document is *imported* — its body arrives, because that is
    what `mandatory` with no statable trigger claims and a list of paths under a
    heading is only a recommendation. An **advertised** Document contributes one
    line: enough that nothing can be missed out of ignorance, not enough to cost
    anything. An **on-demand** Document contributes nothing at all.
    """
    lines = [
        BEGIN,
        "",
        "## Knowledge this project has adopted",
        "",
        "Everything below is vendored under `.luma/bundles/` and is part of this "
        "repository.",
        "",
    ]

    standing = [d for b in bundles for d in b.of_class("standing")]
    if standing:
        lines += [
            "**These are in force here and are loaded with this file.** Each one "
            "is `compliance: mandatory` with no condition narrowing when it "
            "applies, so it governs everything done in this repository.",
            "",
        ]
        for doc in standing:
            rel = doc.path.relative_to(project_root).as_posix()
            lines.append(f"@{rel}")
        lines.append("")

    for bundle in bundles:
        home = bundle.root.relative_to(project_root).as_posix()
        heading = f"### `{bundle.bundle_id}`"
        if bundle.version:
            heading += f" {bundle.version}"
        lines += [heading, ""]
        if bundle.description:
            lines += [bundle.description, ""]

        shown = bundle.of_class("advertised")
        if not shown:
            lines += [f"Nothing here applies conditionally. In `{home}/`.", ""]
            continue

        lines += [
            f"In `{home}/` — **open one when the work matches its line**, and "
            "not before:",
            "",
        ]
        for doc in sorted(shown, key=lambda d: (d.type, d.doc_id)):
            note = doc.description or doc.title or ""
            when = ", ".join(doc.applies_to)
            teeth = " **[blocked]**" if doc.on_violation == "block" else ""
            lines.append(f"- `{doc.doc_id}` ({doc.type}){teeth} — {note}".rstrip(" —"))
            if when:
                lines.append(f"  - applies to: {when}")
        lines.append("")

    lines += [
        "Workflows here are also installed as skills, so they can be invoked by "
        "name. Everything under `.luma/bundles/` is a copy — change it upstream "
        "and re-adopt, never in place.",
        "",
        END,
    ]
    return "\n".join(lines)


def _splice(existing: str, block: str) -> str:
    """Put *block* into *existing*, touching nothing outside the markers.

    A project's `CLAUDE.md` is mostly hand-written and belongs to whoever wrote
    it. Owning a delimited region of it is the most that can be taken without
    destroying somebody's work, and it is enough.
    """
    start = existing.find(BEGIN)
    end = existing.find(END)
    if start != -1 and end != -1 and end > start:
        return existing[:start] + block + existing[end + len(END) :]
    if not existing.strip():
        return block + "\n"
    return existing.rstrip("\n") + "\n\n" + block + "\n"


# --------------------------------------------------------------------------
# the routing table


def _toml_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _routing(bundles: list[Bundle], project_root: Path) -> str:
    """Every Document with a trigger: when it fires, and what happens then.

    **Compiled once and read by everything**, which is what keeps the gate and a
    future router from drifting apart. `on_violation` is one column of this
    table rather than a table of its own — blocking is simply its first
    consumer.

    It must be compiled rather than derived live: the gate runs before **every**
    tool call against a budget measured in milliseconds, and walking
    `.luma/bundles/` to parse frontmatter per call would spend it several times
    over.
    """
    lines = [
        "# Generated by `luma-foreman outfit`. Edits are lost.",
        "#",
        "# Every Document that says when it applies, and what happens when it is",
        "# not complied with. The permission gate reads the rows that block; it",
        "# cannot be told to ignore them, and nothing in `agent-permissions`",
        "# writes here.",
        "",
    ]
    for bundle in bundles:
        for doc in bundle.docs:
            if not doc.applies_to:
                continue
            rel = doc.path.relative_to(project_root).as_posix()
            lines += [
                "[[rule]]",
                f"bundle = {_toml_str(bundle.bundle_id)}",
                f"document = {_toml_str(doc.doc_id)}",
                f"title = {_toml_str(doc.title or doc.doc_id)}",
                f"path = {_toml_str(rel)}",
                f"compliance = {_toml_str(doc.compliance)}",
                f"on_violation = {_toml_str(doc.on_violation)}",
                "applies_to = ["
                + ", ".join(_toml_str(a) for a in doc.applies_to)
                + "]",
                "",
            ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# the command


def _gate_installed() -> bool:
    """Is the hook that would honour a `block` actually wired into the harness?

    Declaring blocking where nothing intercepts produces a rule that **reads as
    enforced and is not** — a guardrail in the index and a label in reality.
    That is the failure this design exists to remove, so it is worth a warning
    rather than a silent nothing.
    """
    try:
        from .agent_permissions import install

        return bool(install.wiring().get("hook_ok"))
    except Exception:
        return False


def _refusals(bundles: list[Bundle]) -> list[str]:
    """Declarations this build cannot honour. Each one stops the run.

    The alternative is silently doing the nearest thing that works — a rule
    asking to be blocked becoming a line of prose — which is a rule that is
    weaker than it says and nobody finding out.
    """
    out = []
    for bundle in bundles:
        for doc in bundle.docs:
            if doc.on_violation not in SUPPORTED_ON_VIOLATION:
                out.append(
                    f"{bundle.bundle_id} {doc.doc_id}: on_violation "
                    f"'{doc.on_violation}' is not implemented"
                )
    return out


def _notices(bundles: list[Bundle], project_root: Path) -> list[str]:
    """Things worth saying that are not worth stopping for."""
    out = []
    for bundle in bundles:
        for doc in bundle.docs:
            # `preload` is read only so it can be reported. Honouring it would
            # let a half-migrated bundle behave correctly and stall there
            # forever, which is the one outcome a migration cannot survive.
            if doc.legacy_preload:
                out.append(
                    f"{bundle.bundle_id} {doc.doc_id}: still declares "
                    f"preload — replace with compliance and applies_to"
                )
            # A glob matching nothing never fires, and silence is
            # indistinguishable from a rule that has simply not come up. Saying
            # so is the difference between *does not apply* and *will never be
            # seen*.
            for trigger in doc.applies_to:
                kind, _, value = trigger.partition(":")
                if kind != "path" or not value:
                    continue
                try:
                    if next(project_root.glob(value), None) is None:
                        out.append(
                            f"{bundle.bundle_id} {doc.doc_id}: nothing in this "
                            f"project matches '{value}' — the rule can never fire"
                        )
                except (ValueError, OSError):
                    continue
    return out


def run(project_root: Path, check: bool) -> int:
    bundles = discover(project_root)
    if not bundles:
        print(
            "nothing adopted — .luma/bundles/ holds no bundles.\n"
            "  luma-foreman adopt --list --from <catalog>",
            file=sys.stderr,
        )
        return 2

    refused = _refusals(bundles)
    if refused:
        print("cannot project — declarations this build cannot honour:", file=sys.stderr)
        for line in refused:
            print(f"  {line}", file=sys.stderr)
        return 2

    planned: dict[Path, str] = {}
    chosen, collided = _names(bundles)
    skills = project_root / ".claude" / "skills"
    for name, doc in chosen.items():
        bundle = next(b for b in bundles if b.bundle_id == doc.bundle)
        planned[skills / name / "SKILL.md"] = _skill(doc, bundle, project_root)

    routing = adoption.bundles_dir(project_root) / "routing.toml"
    planned[routing] = _routing(bundles, project_root)

    claude = project_root / "CLAUDE.md"
    current = claude.read_text(encoding="utf-8") if claude.is_file() else ""
    planned[claude] = _splice(current, _index(bundles, project_root))

    stale = [p for p in _generated(skills).values() if p.name not in chosen]
    changed = [
        path
        for path, content in planned.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]

    if check:
        for path in sorted(changed):
            print(f"stale: {path.relative_to(project_root).as_posix()}")
        for path in sorted(stale):
            print(f"orphan: {path.relative_to(project_root).as_posix()}")
        if changed or stale:
            print("\nrun `luma-foreman outfit`")
            return 1
        print("up to date")
        return 0

    for path, content in planned.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    for path in stale:
        shutil.rmtree(path)

    workflows = sum(len(b.of_type("workflow")) for b in bundles)
    counts = {k: sum(len(b.of_class(k)) for b in bundles)
              for k in ("standing", "advertised", "on-demand")}
    print(f"{len(bundles)} bundle(s) projected")
    print(f"  skills     {workflows} workflow(s) -> .claude/skills/")
    print(f"  standing   {counts['standing']} loaded with CLAUDE.md")
    print(f"  advertised {counts['advertised']} named, opened when they match")
    print(f"  on-demand  {counts['on-demand']} reachable, not announced")

    blocking = [d for b in bundles for d in b.docs if d.on_violation == "block"]
    if blocking and not _gate_installed():
        print()
        print(
            f"  WARNING  {len(blocking)} rule(s) declare blocking and nothing here "
            f"enforces them.\n"
            f"           The permission gate is not wired into this harness, so a "
            f"rule that\n"
            f"           reads as a guardrail is a label. Install it:\n"
            f"             luma-foreman agent-permissions install"
        )

    for line in _notices(bundles, project_root):
        print(f"  notice   {line}")
    if stale:
        print(f"  removed  {len(stale)} skill(s) for bundles no longer here")
    if collided:
        print()
        print(
            "  note: these workflow names appear in more than one bundle and "
            "were\n        prefixed on both sides so neither is unreachable: "
            + ", ".join(collided)
        )
    if not changed and not stale:
        print("\n  (nothing changed)")
    else:
        print("\n  Commit the result, or gitignore .claude/ — it is generated either way.")
    return 0


def main(argv: list[str]) -> int:
    check = False
    target: Path | None = None
    rest = list(argv)
    while rest:
        arg = rest.pop(0)
        if arg in ("-h", "--help"):
            print(USAGE)
            return 0
        if arg == "--check":
            check = True
        elif arg == "--to":
            if not rest:
                print("luma-foreman outfit: --to needs a directory", file=sys.stderr)
                return 2
            target = Path(rest.pop(0))
        else:
            print(f"luma-foreman outfit: unknown option: {arg}", file=sys.stderr)
            return 2

    if target and not target.is_dir():
        print(f"luma-foreman outfit: not a directory: {target}", file=sys.stderr)
        return 2
    project_root, _ = project.resolve(target or Path.cwd())
    return run(project_root, check)
